services:
  - type: web
    name: addismusc-backend
    env: docker
    plan: free
    rootDir: Server
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
